# Generated by Django 3.1.7 on 2021-03-17 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_item_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='interested', to=settings.AUTH_USER_MODEL),
        ),
    ]
